### ISSUE TITLE
Problems on utilFunctions_C

### ISSUE THREAD

**Issue by jerermyyoung** [georgid/vocal-detection#1]
Hi,

I want to reproduce the result of your code, but I encountered with some problems. Here's the log:

```
(yanghs_torch) [zhangwq02@r830-004 vocal-detection]$ python main.py
[   INFO   ] MusicExtractorSVM: no classifier models were configured by default
/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/sklearn/utils/__init__.py:12: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .murmurhash import murmurhash3_32
/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/sklearn/utils/extmath.py:23: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._logistic_sigmoid import _log_logistic_sigmoid
/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/sklearn/utils/extmath.py:25: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .sparsefuncs_fast import csr_row_norms
/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/sklearn/metrics/cluster/supervised.py:25: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .expected_mutual_info_fast import expected_mutual_information
/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/sklearn/metrics/pairwise.py:31: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .pairwise_fast import _chi2_kernel_fast, _sparse_manhattan
/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/sklearn/tree/tree.py:40: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._criterion import Criterion
/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/sklearn/neighbors/__init__.py:6: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .ball_tree import BallTree
/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/sklearn/neighbors/__init__.py:7: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .kd_tree import KDTree
/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/sklearn/utils/random.py:10: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._random import sample_without_replacement
/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._gradient_boosting import predict_stages
/home/zhangwq02/yanghansi/vocal-detection/smstools/software/models/utilFunctions_C/
['/home/zhangwq02/yanghansi/vocal-detection', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python27.zip', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/plat-linux2', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/lib-tk', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/lib-old', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/lib-dynload', '/home/zhangwq02/.local/lib/python2.7/site-packages', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/mir_eval-0.5-py2.7.egg', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info', '/home/zhangwq02/yanghansi/vocal-detection/smstools/workspace/../software/models/', '/home/zhangwq02/yanghansi/vocal-detection/smstools/software/models/utilFunctions_C/']
/home/zhangwq02/yanghansi/vocal-detection/smstools/software/models/utilFunctions_C/
['/home/zhangwq02/yanghansi/vocal-detection', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python27.zip', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/plat-linux2', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/lib-tk', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/lib-old', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/lib-dynload', '/home/zhangwq02/.local/lib/python2.7/site-packages', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/mir_eval-0.5-py2.7.egg', '/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info', '/home/zhangwq02/yanghansi/vocal-detection/smstools/workspace/../software/models/', '/home/zhangwq02/yanghansi/vocal-detection/smstools/software/models/utilFunctions_C/', '/home/zhangwq02/yanghansi/vocal-detection/smstools/software/models/utilFunctions_C/']
/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/sklearn/base.py:253: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version pre-0.18 when using version 0.20.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/sklearn/base.py:253: UserWarning: Trying to unpickle estimator RandomForestClassifier from version pre-0.18 when using version 0.20.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
[wav @ 0x55555f09d280] Using AVStream.codec.time_base as a timebase hint to the muxer is deprecated. Set AVStream.time_base instead.
[wav @ 0x55555f09d280] Encoder did not produce proper pts, making some up.
/home/zhangwq02/anaconda3/envs/yanghs_torch/lib/python2.7/site-packages/mir_eval-0.5-py2.7.egg/mir_eval/multipitch.py:168: RuntimeWarning: divide by zero encountered in log2
no peaks detected at time 0 with threshold -70
no peaks detected at time 0 with threshold -70
no peaks detected at time 0 with threshold -70
no peaks detected at time 30 with threshold -70
Traceback (most recent call last):
  File "main.py", line 209, in <module>
    doit(['dummy,', audio_URI, output_URI])
  File "main.py", line 118, in doit
    resynthesize(hfreq, hmag, hphase, fs, hopSizeMelodia, fileWavURI_resynth)
  File "/home/zhangwq02/yanghansi/vocal-detection/smstools/workspace/harmonicModel_function.py", line 107, in resynthesize
    y = SM.sineModelSynth(hfreq, hmag, hphase, Ns, hopSizeMelodia, fs)  
  File "/home/zhangwq02/yanghansi/vocal-detection/smstools/workspace/../software/models/sineModel.py", line 215, in sineModelSynth
    Y = UF.genSpecSines(tfreq[l,:], tmag[l,:], ytphase, N, fs)  # generate sines in the spectrum         
  File "/home/zhangwq02/yanghansi/vocal-detection/smstools/workspace/../software/models/utilFunctions.py", line 142, in genSpecSines
    Y = UF_C.genSpecSines(N*ipfreq/float(fs), ipmag, ipphase, N)
AttributeError: 'module' object has no attribute 'genSpecSines'
```

It seems that the problem came from the UF_C, or utilFunctions_C module. But I know little about that. Can anybody tell me what's really wrong?

**Comment by georgid** [comment]
@jerermyyoung This seems like a problem with the [SMS tools](  https://github.com/MTG/sms-tools) - most probably compiling the Cython code. Make sure you check the installation instructions of the SMS-tools.
